{
 "title": "SINEMA RC",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  { "title": "SINEMA RC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total amount of traffic over SRC in timerange",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\r\n SUM(usage) AS \"Usage\"\r\n FROM userlog\r\nWHERE\r\n  $__timeFilter(time)\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "options": {
    "content": "<img src=\"/public/img/logo_srcdashboard_round.png\" height=\"160\">"
   }
  },
  {
   "title": "Total number of accesses in timerange",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\r\n count(id) AS \"ID\"\r\n FROM userlog\r\nWHERE\r\n  $__timeFilter(time)\r\n"
    }
   ]
  },
  {
   "title": "Last 10 Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\r\n time AS \"Time\",\r\n username AS \"User\",\r\n endpoint AS \"Destination\", \r\n destinationport AS \"Port\",\r\n duration AS \"Duration\"\r\n FROM userlog\r\nOrder BY time DESC\r\nfetch first 10 rows only"
    }
   ]
  },
  {
   "title": "Top 10 Destinations",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\r\n count(endpoint) AS \"Anzahl\", \r\n endpoint AS \"Destination\"\r\n FROM userlog\r\nWHERE\r\n  $__timeFilter(time)\r\nGROUP BY endpoint\r\nOrder BY count(endpoint)DESC\r\nfetch first 10 rows only"
    }
   ]
  },
  {
   "title": "Top 10 User Access",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\r\n count(username) AS \"Anzahl\", \r\n username AS \"User\"\r\n FROM userlog\r\nWHERE\r\n  $__timeFilter(time)\r\nGROUP BY username\r\nOrder BY count(username)DESC\r\nfetch first 10 rows only"
    }
   ]
  },
  {
   "title": "Top 10 used Services",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\r\n count(destinationport) AS \"Anzahl\", \r\n destinationport AS \"Port\"\r\n FROM userlog\r\nWHERE\r\n  $__timeFilter(time)\r\nGROUP BY destinationport\r\nOrder BY count(destinationport)DESC\r\nfetch first 10 rows only"
    }
   ]
  },
  {
   "title": "Top 10 User - Traffic",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\r\n SUM(usage) AS \"Usage\", \r\n username AS \"User\"\r\n FROM userlog\r\nWHERE\r\n  $__timeFilter(time)\r\nGROUP BY username\r\nOrder BY count(username)DESC\r\nfetch first 10 rows only"
    }
   ]
  }
 ]
}